config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do
    resources :bookmarks, only: :create
    resources :orders, only: :create
  end

  resources :orders, only: %i[index show edit update] do
    resources :messages, only: %i[index create]
    resources :reviews, only: %i[new create]
  end

  resources :bookmarks, only: :destroy
  resources :users, only: %i[show edit update]

  get '/orders/:id/update_done', to: "orders#update_done"
  get '/products/new/scan', to: "products#scan"
  get '/thanks', to: "pages#thanks"
  get '*unmatched_route', to: 'products#index'
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=asset_path("banner.jpg")%>);">
  <div class="container">
    <h1 class="mb-2">Stop Waste, just sell it !</h1>
  <%=render "shared/searchbar"%>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="d-flex align-items-center justify-content-between p-3">
    <div class="footer-links">
      <a href="/thanks"><i class="fab fa-github"></i></a>
      <a href="/thanks"><i class="fab fa-twitter"></i></a>
      <a href="/thanks"><i class="fab fa-linkedin"></i></a>
      <a href="/thanks"><i class="fab fa-facebook"></i></a>
      <a href="/thanks"><i class="fab fa-linkedin"></i></a>
    </div>
      <a href="/thanks"><i class="fa-solid fa-phone me-1"></i>Contact us</p>

    <div class="footer-copyright">
      <a href="/thanks"><i class="fa-solid fa-copyright 2022 me-1"></i> 2022 Waste Market </a>
    </div>
  </div>
</div>

app/views/shared/_footer_navbar.html.erb
<footer role="navbar navbar-fixed-bottom" class="mobilenavbarfooter navbar-expand invisible-scrollbar fixed-bottom al-sm-dark-green">
  <div class="container-fluid">
      <div class="navbar-nav justify-content-sm-around align-items-center w-100 h-100">
        <a href="#"><span class="fa-sm mr-sm-2 icon"><i class="fa-solid fa-house"></i></span></a>
        <a href="#"><span class="fa-sm mr-sm-2 icon"><i class="fa fa-user-circle"></i></span></a>
        <a href="#"><span class="fa-sm mr-sm-2 icon"><i class="fa-solid fa-message"></i></span></a>
        <ul>
  </div>
</footer>

app/views/shared/_mobilenavbar.html.erb
<!-- mobile navbar fixed bottom -->
<footer role="mobilenavbar navbar-fixed-bottom" class="mobilenavbarfooter navbar-expand invisible-scrollbar fixed-bottom al-sm-dark-green">
  <%= link_to root_path do %>
    <%# <div class="display-flex-element style"> %>
    <a href="/" class="text-reset">
      <span class="fa-stack" style="vertical-align: top;">
        <i class="fa-solid fa-circle fa-stack-2x color-creme"></i>
        <i class="fa-solid fa-house fa-stack-1x fa-inverse"></i>
      </span>
  <% end %>

    <% if user_signed_in? %>
      <%= link_to user_path(current_user) do %>
        <%= image_tag (current_user.photo.attached? ? cl_image_path(current_user.photo.key) : asset_path("emy.jpg")), class: "avatar" %>
      <% end %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "color-creme" %>
    <% end %>

    <span class="fa-stack" style="color: white vertical-align: top;">
  <%= link_to root_path do %>
      <i class="fa-solid fa-circle fa-stack-2x color-creme"></i>
      <% end %>
      <%= link_to orders_path do %>
      <i class="fa-solid fa-message fa-stack-1x fa-inverse"></i>
  <% end %>
    </span>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag asset_path("Logo.png") %>
    <% end %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", orders_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New product", '/products/new/scan', class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag (current_user.photo.attached? ? cl_image_path(current_user.photo.key) : asset_path("emy.jpg")), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<%= simple_form_for :searchbar, url: products_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>