config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do
    resources :bookmarks, only: :create
    resources :orders, only: :create
  end

  resources :orders, only: %i[index show edit update] do
    resources :messages, only: %i[index create]
    resources :reviews, only: %i[new create]
  end

  resources :bookmarks, only: :destroy
  resources :users, only: %i[show edit update]

  get '/orders/:id/update_done', to: "orders#update_done"
  get '/products/new/scan', to: "products#scan"
  get '/thanks', to: "pages#thanks"
  get '*unmatched_route', to: 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  belongs_to :category, class_name: "Category"
  belongs_to :sub_category, class_name: "SubCategory"
  has_one_attached :photo
  # validates :name, presence: true
  # validates :price, presence: true
  # validates :category, presence: true
  # validates :sub_category, presence: true
  # validates :condition, presence: true
  # validates :quantity_left, presence: true
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :brand, :condition, :characteristics, :description ],
    associated_against: {
      category: :name,
      sub_category: :name
    },
    using: {
      tsearch: { prefix: true }
    }

  def user_bookmark(user)
    bookmarks.find_by(user: user)
  end
end

app/controllers/products_controller.rb
include CloudinaryHelper
require 'open-uri'

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @categories = Category.all
    if params[:category]
      @products = Product.where(category_id: params[:category], EAN: nil).order(created_at: :desc)
    elsif params[:search]
      @products = Product.global_search(params[:search][:query]).where(EAN: nil).order(created_at: :desc)
    else
      @products = Product.where(EAN: nil).order(created_at: :desc)
    end
  end

  def show
    @markers = [{
      lat: @product.user.latitude,
      lng: @product.user.longitude,
      info_window: render_to_string(partial: "info_window", locals: { product: @product }),
      image_url: helpers.asset_url(@product.user.photo.attached? ? CloudinaryHelper.cl_image_path(@product.user.photo.key) : "/assets/images/emy.jpg")
    }]
  end

  def new
    @scan = params[:scan]
    @product_scanned = Product.find_by(EAN: @scan) if @scan
    @product = Product.new
  end

  def create
    @user = current_user
    @product = Product.new(product_params)
    @product.user = @user
    @scan = params[:product][:scan]
    @product_scanned = Product.find_by(EAN: @scan) if @scan
    @product.photo.attach(io: URI.open(cl_image_path(@product_scanned.photo.key)), filename: "#{@product.name}.jpg") if @product_scanned
    if @product.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @user = current_user
    @product.destroy
    if request.referer.include?('users')
      redirect_to user_path(current_user, notice: 'Product was successfully destroyed.')
    else
      redirect_to products_path, notice: 'Product was successfully destroyed.'
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :category_id, :sub_category_id, :characteristics, :quantity_left, :brand, :condition, :quantity_left, :buying_date, :expiration_date, :photo)
  end
end

app/views/products/_card.html.erb
<div class="card-product">
  <%# Display Product image %>
  <%= link_to product_path(product) do %>
    <%= image_tag (product.photo.attached? ? cl_image_path(product.photo.key) : asset_path("paintpots.jpg"))%>
  <% end %>

  <%# Display Product information %>
  <div class="card-product-infos">
    <div class="card-product-infos-primary">
      <h2><%= product.name %></h2>
      <h3><%= product.category.name %></h3>
      <p><%= product.user.address %></p>
    </div>
    <div class="card-product-infos-secondary">
      <p><%= product.price %> €</p>
      <p><%= product.quantity_left %> %</p>
    </div>
  </div>

  <%# Display Bookmark button for buyers %>
  <div class="card-buttons">
      <%# if product.id == @bookmark.product_id  %>
        <%#= link_to product_bookmarks_path(product) do %>
          <i class="fa-solid fa-heart"></i>
        <%# end %>
      <%# else %>
        <%#= link_to bookmarks_path(bookmark), method: :delete, data: { confirm: "Are you sure?" } do %>
          <%#  %><i class="fa-regular fa-heart"></i>
        <%# end %>
      <%# end %>
  </div>

  <%# Display edit and delete button for sellers %>
  <% if product.user == current_user  %>
    <div class="card-buttons">
      <%= link_to edit_product_path(product) do %>
        <i class="fa-regular fa-pen-to-square"></i>
      <% end %>
      <%= link_to product_path(product), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa-regular fa-trash-can-xmark"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/products/_card_category.html.erb
<%= link_to products_path(category: category, anchor: "products-anchor") do %>
  <% picture_name = category.name + ".jpg" %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=asset_path(picture_name)%>)">
    <%= category.name.capitalize %>
  </div>
<% end %>

app/views/products/_card_product.html.erb
<div class="card-product" id="product-<%= product.id %>">
  <%# Display Product image %>
  <%= link_to product_path(product) do %>
    <% picture_name = product.category.name + ".jpg" %>
    <%= image_tag (product.photo.attached? ? cl_image_path(product.photo.key) : asset_path(picture_name)), class: "product-card-image"%>
  <% end %>

  <%# Display User avatar %>
  <%= link_to user_path(product.user) do %>
    <%= image_tag (product.user.photo.attached? ? cl_image_path(product.user.photo.key) : asset_path("emy.jpg")), class: "avatar-on-card position-avatar-cardproduct" %>
  <% end %>

  <%# display product title  %>
  <div class="card-product-title">
    <h2><%= product.name.capitalize %></h2>
  </div>

  <%# Display Product information %>
  <div class="card-product-infos">
    <div class="card-product-infos-primary">
      <h3 class="card-category-name"><%= product.category.name.capitalize %></h3>
      <p class="card-category-address"><%= product.user.address.split(" ").last %></p>
    </div>
    <div class="card-product-infos-secondary">
      <h3><%= product.price %> €</h3>
      <% if product.quantity_left %>
        <div id="order-gauge-product" data-controller="gauge" data-gauge-pourcentage-value="<%= product.quantity_left%>"></div>
      <% end %>
    </div>
  </div>

  <%# Display Bookmark button for buyers %>
  <% if current_user && current_user.not_my_product?(product) %>
    <div class="card-buttons">
      <% bookmark = product.user_bookmark(current_user)  %>
        <% if bookmark %>
          <%= link_to bookmark_path(bookmark), remote: true, method: :delete do %>
            <i class="fa-solid fa-heart"></i>
          <% end %>
        <% else %>
        <%= link_to product_bookmarks_path(product), remote: true, method: :post do %>
          <i class="fa-regular fa-heart"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <%# Display edit and delete button for sellers %>
  <% if current_user && product.user == current_user  %>
    <div class="card-buttons">
      <%= link_to edit_product_path(product) do %>
        <i class="fa-regular fa-pen-to-square"></i>
      <% end %>
      <!-- Button modal delete -->
      <%= link_to "#", data: { bs_toggle: "modal", bs_target: "#modal-delete-product-#{product.id}"} do %>
        <i class="fa-regular fa-trash-can"></i>
      <% end %>

      <!-- Modal -->
      <div class="modal fade" id="modal-delete-product-<%=product.id%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Confirmation delete</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Would you like to delete this product?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <%= button_to 'Delete', product_path(product), method: :delete, class:"btn-pink" %>
            </div>
          </div>
        </div>
      </div>

    </div>
  <% end %>
</div>
 <%#= link_to 'Yes', order_path(order, progress: "cancelled", notice: "Order cancelled"), method: :patch, class:"btn-green-primary" %>

app/views/products/_form_products.html.erb
<div data-controller="swal">
  <%= simple_form_for(@product, html: { data: { swal_target: "swalform" } } ) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <div id="smartwizard">
        <ul class="nav">
          <li>
              <a class="nav-link" href="#step-1">
                  Product info
              </a>
          </li>
          <li>
              <a class="nav-link" href="#step-2">
                  Your details
              </a>
          </li>
          <li>
              <a class="nav-link" href="#step-3">
                  Waste Market fair price proposal
              </a>
          </li>
        </ul>

        <div class="tab-content tab-content-categories" data-controller="quantity-left" data-price= "<%=@product_scanned&.price || @product&.price %>">
          <div id="step-1" class="tab-pane" role="tabpanel">
              <%= f.input :name, input_html: {value: @product_scanned&.name || @product&.name }%>
              <%= f.input :description, input_html: {value: @product_scanned&.description || @product&.description} %>
              <%= f.association :category, collection: Category.all.map{|cat| [cat.name.capitalize, cat.id]}, prompt: "Choose a Category", selected: @product_scanned&.category&.id %>
              <%= f.association :sub_category, collection: SubCategory.all, prompt: "Choose a Sub Category", selected: @product_scanned&.sub_category&.id %>
              <%= f.input :characteristics, input_html: {value: @product_scanned&.characteristics || @product&.characteristics }%>
              <%= f.input :brand, input_html: {value: @product_scanned&.brand || @product&.brand } %>
              <%= f.input :photo, as: :file unless @product_scanned %>
              <%= f.hidden_field :scan, value: params[:scan] %>
          </div>
          <div id="step-2" class="tab-pane container" role="tabpanel">
            <div class="d-flex justify-content-between">
              <%= f.input :quantity_left,
                          as: :radio_buttons,
                          collection: [["25 %", 25], ["50 %", 50], ["75 %", 75], ["100 %", 100]],
                          input_html: {
                            class: "sr-only",
                            data: {
                              quantity_left_target: "quantity",
                              radio_buttons_target: "input",
                              action: "change->quantity-left#test radio-buttons#select"
                              }
                          },
                          wrapper_html: { class: "mb-4", data: {controller: "radio-buttons"} },
                          item_label_class: "radio-form",
                          item_wrapper_class: "custom-radio-buttons" %>
               <%= f.input :price, label: "Proposed price in €", input_html: { data: { quantity_left_target: "price" }, value:
                  @product&.price}%>
            </div>
              <%= f.input :condition,
                          as: :radio_buttons,
                          collection: ["Perfect", "Good", "Average", "Poor"].map { |element| [element, element] },
                          input_html: {
                            class: "sr-only",
                            data: {
                              radio_buttons_target: "input",
                              action: "change->quantity-left#test radio-buttons#select"
                              }
                          },
                          wrapper_html: { class: "mb-4", data: {controller: "radio-buttons"} },
                          item_label_class: "radio-form",
                          item_wrapper_class: "custom-radio-buttons" %>
              <%= f.input :buying_date,
                  as: :radio_buttons,
                  collection: ["Less than 3 months", "Less than 6 months", "Less than a year", "More than a year"].map { |element| [element, element] },
                  input_html: {
                    class: "sr-only",
                    data: {
                      radio_buttons_target: "input",
                      action: "change->quantity-left#test radio-buttons#select"
                      }
                  },
                  wrapper_html: { class: "mb-4", data: {controller: "radio-buttons"} },
                  item_label_class: "radio-form",
                  item_wrapper_class: "custom-radio-buttons" %>
              <%= f.input :expiration_date, as: :radio_buttons,
                  collection: ["Less than 3 months", "Less than 6 months", "Less than a year", "More than a year"].map { |element| [element, element] },
                  input_html: {
                    class: "sr-only",
                    data: {
                      radio_buttons_target: "input",
                      action: "change->quantity-left#test radio-buttons#select"
                      }
                  },
                  wrapper_html: { class: "mb-4", data: {controller: "radio-buttons"} },
                  item_label_class: "radio-form",
                  item_wrapper_class: "custom-radio-buttons" %>
          </div>
          <div id="step-3" class="tab-pane" role="tabpanel">
              <%= f.input :price, label: "Happy with this price ? If not, feel free to change it!", input_html: {class: "price-final", data: { quantity_left_target: "price" }, value:
                            if @product_scanned
                               @product_scanned&.price * (@product_scanned&.quantity_left.to_i.fdiv(100))
                            end || @product&.price} %>


          </div>
        </div>
      </div>
    </div>
    <%= javascript_pack_tag 'smartwizard' %>
  <% end %>
</div>

app/views/products/_info_window.html.erb
<h2><%= @product.name %></h2>
<p><%= @product.user.address %></p>

app/views/products/_list_products.html.erb
<% products.each do |product| %>
  <%= render 'products/card_product', product: product %>
<% end %>

app/views/products/edit.html.erb
<!-- CSS -->
<link href="https://cdn.jsdelivr.net/npm/smartwizard@5/dist/css/smart_wizard_all.min.css" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<!-- JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/smartwizard@5/dist/js/jquery.smartWizard.min.js" type="text/javascript"></script>

  <%= link_to 'Back', user_path(@product.user_id), class: "btn-green-secondary" %>

  <h1 class="text-center">Edit my product</h1>

  <%= render 'form_products', teacher: @product %>

app/views/products/index.html.erb
<h2> Top Categories</h2>

<div class="cards-categories">
  <% @categories.each do |category| %>
    <%= render 'products/card_category', category: category %>
  <% end %>
</div>


<h2 id="products-anchor">Trending products</h2>

<div class="cards-products">
  <% @products.each do |product| %>
    <%= render 'products/card_product', product: product%>
  <% end %>
</div>
<br>
<br>
<br>

app/views/products/new.html.erb
<div class="position-relative back-button my-5">
  <%= link_to 'Back', products_new_scan_path, class: "btn-pink position-absolute left-0" %>
  <h1 class="text-center">New product</h1>

</div>
<%= render 'form_products', product: @product %>

app/views/products/scan.html.erb
<h1 class= "text-center mb-2" id="scan">Please scan your product</h1>
<h2 class= "text-center">Don't have anything to scan ?</h2>
<div class= "d-flex justify-content-center mt-1">
  <br>
  <%= link_to 'Add a product without scanning', new_product_path, class: "btn-green-primary" %>
  </div>
</div>
<div class= "d-flex justify-content-center mt-2">
  <div id="scandit-barcode-picker" style="max-width: 700px;" data-controller="scan"></div>
  <br>
</div>

app/views/products/show.html.erb
<div class="product-show">

<%# buttons action %>
<% if current_user&.can_order?(@product) %>
<%= link_to product_orders_path(@product), method: :post do %>
  <div class="order-sm"><i class="fa-solid fa-cart-arrow-down"></i></div>
<% end %>
  <div class="product-show-buttons-right">
    <%= button_to 'Order', product_orders_path(@product), method: :post, class: "btn-green-primary"%>
  </div>
<% end %>
<div class="product-show-buttons-left">
  <%= link_to 'Back', root_path, class: "btn-pink" %>
</div>


<div class="row justify-content-center">
  <div class="col-12 col-md-8 col-lg-6">
    <div class="product-show-card">
      <%# start header links %>
      <%# end header links %>

      <%# Display user infos %>
        <%# Display User avatar %>
        <%#= link_to user_path(@product.user) do %>
          <%#= image_tag (@product.user.photo.attached? ? cl_image_path(@product.user.photo.key) : asset_path("emy.jpg")), class: "" %>
        <%# end %>
        <%# Display User infos %>
        <%# <p><%= @product.user.username %>
        <%# <p>DISPLAY USER INFO HERE </p> %>

      <%# start block infos product %>
      <section class="row mt-3 product-infos">
        <div class="col-12">
          <div class="d-flex justify-content-between">
            <h1 class="text-uppercase"><span>
              <%= @product.name %>
              <i class='fa fa-share-alt' class="p-2 bd-highlight"></i>
                <%# Display Bookmark button for buyers %>
                <% if current_user && @product.user != current_user %>
                  <span class="ms-2">
                    <% if current_user.bookmarks.find_by(product: @product) %>
                      <% bookmark = current_user.bookmarks.find_by(product: @product) %>
                      <%= link_to bookmark_path(bookmark), method: :delete do %>
                        <i class="fa-solid fa-heart"></i>
                      <% end %>
                    <% else %>
                      <%= link_to product_bookmarks_path(@product), method: :post do %>
                        <i class="fa-regular fa-heart"></i>
                      <% end %>
                    <% end %>
                  </span>
                <% end %>
            </span></h1>

            <div class="product-price">
              <i class="fa-solid fa-tag text-"></i>
              <span class="fw-bold"><%= @product.price %>€</span>
            </div>
          </div>
        </div>

        <div class="col-6">
          <h3 class="my-1"><%= @product.brand %></h3>
          <h3 class="my-1"><%= @product.category.name.capitalize %> - <%= @product.sub_category.name.capitalize %></h3>
          <div class="small my-1"><%= @product.characteristics %></div>
        </div>

        <div class="col-6">
          <div>
            <div id="gaugeArea" class="text-end" data-controller="gauge" data-gauge-pourcentage-value="<%= @product.quantity_left%>"></div>
          </div>
        </div>

        <div class="col-12">
          <div>
            <span>Condition : </span>
            <span>
              <%= @product.condition %>
            </span>
          </div>
          <div class="d-flex justify-content-between mt-1">
            <span>
              <i class='fa fa-calendar'></i>
              <span class="ms-1">Use before : </span>
              <% if @product.expiration_date %>
                <%= @product.expiration_date %>
              <% else %>
                <span class="fst-italic">Unknown</span>
              <% end %>
            </span>
            <span>
              <span class="ms-1">
                <i class='fa fa-calendar'></i>
                Purchased :
              </span>
              <% if @product.buying_date %>
                <%= @product.buying_date %>
              <% else %>
                <span class="fst-italic">Unknown</span>
              <% end %>
            </span>
          </div>
        </div>
      </section>
      <%# end block infos product %>

      <%# start block description product %>
      <section class="row mx-0 my-3 py-2 small product-description">
        <div class="col-6">
          <h2 class="mb-1">Description Product</h2>

          <%= @product.description %>
        </div>
        <div class="col-6 d-flex align-items-center">
          <% if @product.photo.attached? %>
            <%= cl_image_tag(@product.photo.key, alt: @product.name) %>
          <% else %>
            <% picture_name = @product.category.name + ".jpg" %>
            <%= image_tag(picture_name, class: "img-fluid")%>
          <% end %>
        </div>
      </section>

    <%# start map %>
    <div style="width: 100%; height: 300px;"
      class="mt-3"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    <%# end map %>

    </div>
  </div>
</div>

app/views/products/show_new.html.erb
<div class="product-show">
  <h1 class="text-align-center"><%= @product.name.capitalize %></h1>
    <%# start buttons action %>
    <div class="product-show-btn">
      <%= link_to 'Contact', user_path(@product.user_id), class: "btn-green-secondary" %>
      <%= button_to 'Order', product_orders_path(@product), method: :post, class: "btn-green-primary"%>
    </div>

    <%# container for infos %>
    <div class="container-product-show">
      <div class="first-pane">
        <%# Display picture %>
        <div class = "product-show-picture">
          <% if @product.photo.attached? %>
            <%= cl_image_tag(@product.photo.key, alt: @product.name) %>
          <% else %>
            <% picture_name = @product.category.name + ".jpg" %>
            <%= image_tag(picture_name)%>
          <% end %>
        </div>
        <%# Display map %>
        <div class = "product-show-map"
          data-controller="mapbox"
          data-mapbox-markers-value="<%= @markers.to_json %>"
          data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>

      <%# display infos product %>
      <div class="second-pane">
        <div class="product-price">
          <i class="fa-solid fa-tag text-"></i>
          <span class="fw-bold"><%= @product.price %>€</span>
        </div>
        <div>
          <div class="text-muted my-1">Brand: <%= @product.brand %></div>
          <div class="text-dark my-1">Category: <%= @product.category.name.capitalize %></div>
          <div class="text-dark my-1">Sub-category: <%= @product.category.name.capitalize %></div>
          <div class="text-dark small my-1"><%= @product.characteristics %></div>
        </div>
        <div>
          <div id="gaugeArea" class="text-end" data-controller="gauge" data-gauge-pourcentage-value="<%= @product.quantity_left%>"></div>
        </div>
        <div>
          <span>Condition : </span>
          <span>
            <%= @product.condition %>
          </span>
        </div>

        <div>
          <div>
            <i class='fa fa-calendar'></i>
            <span class="ms-1">Use before : </span>
            <% if @product.expiration_date %>
              <%= @product.expiration_date %>
            <% else %>
              <span class="fst-italic">Unknown</span>
            <% end %>
          </div>
          <div>
            <i class='fa fa-calendar'></i>
            <span class="ms-1">
              Purchased :
            </span>
            <% if @product.buying_date %>
              <%= @product.buying_date %>
            <% else %>
              <span class="fst-italic">Unknown</span>
            <% end %>
          </div>
        </div>

      </div>

      <%# display description product %>
      <div class = "third-pane" >
        <h2>Description Product</h2>
        <p><%= @product.description %></p>
      </div>
    </div>
</div>